### ISSUE TITLE
Crash in Stabilize

### ISSUE THREAD

**Issue by lessthanoptimal** [lessthanoptimal/BoofAndroidDemo#12]
java.lang.IllegalArgumentException: end must be more than start. 246 -> 240
	at boofcv.concurrency.BoofConcurrency.loopBlocks(BoofConcurrency.java:160)
	at boofcv.alg.distort.ImageDistortBasic_SB_MT.applyOnlyInside(ImageDistortBasic_SB_MT.java:96)
	at boofcv.alg.distort.ImageDistortBasic.apply(ImageDistortBasic.java:97)
	at boofcv.alg.sfm.d2.StitchingFromMotion2D.update(StitchingFromMotion2D.java:213)
	at boofcv.alg.sfm.d2.StitchingFromMotion2D.process(StitchingFromMotion2D.java:143)
	at org.boofcv.android.sfm.StabilizeDisplayActivity$PointProcessing.process(StabilizeDisplayActivity.java:197)
	at org.boofcv.android.sfm.StabilizeDisplayActivity$PointProcessing.process(StabilizeDisplayActivity.java:137)
	at org.boofcv.android.DemoCamera2Activity.processImage(DemoCamera2Activity.java:248)
	at boofcv.android.camera2.VisualizeCamera2Activity.processImageOuter(VisualizeCamera2Activity.java:396)
	at boofcv.android.camera2.VisualizeCamera2Activity.lambda$processFrame$0(VisualizeCamera2Activity.java:373)
	at boofcv.android.camera2.-$$Lambda$VisualizeCamera2Activity$T8G5xpDdSlcNLrSA-JCgWJEnXfQ.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Comment by lessthanoptimal** [comment]
This could happen if an invalid region is feed to distort. In 0.36 distort has been modified to check to see if a valid range is specified. if not it does nothing.
