### ISSUE TITLE
Runtime crash

### ISSUE THREAD

**Issue by YinXiuYu** [lessthanoptimal/BoofAndroidDemo#24]
2022-08-10 14:01:53.319 3360-3430/org.boofcv.android E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: org.boofcv.android, PID: 3360
    java.lang.NoSuchMethodError: No virtual method resize(I)V in class Lorg/ddogleg/struct/DogArray_I8; or its super classes (declaration of 'org.ddogleg.struct.DogArray_I8' appears in /data/app/~~Om6nvzRjSXiDjKK1z2iHsw==/org.boofcv.android-bHhc5yt_XahFlHFOIhed1A==/base.apk!classes23.dex)
        at boofcv.misc.BoofMiscOps.checkDeclare(BoofMiscOps.java:819)
        at boofcv.core.encoding.impl.ImplConvertYuv420_888.processYuv(ImplConvertYuv420_888.java:50)
        at boofcv.core.encoding.ConvertYuv420_888.yuvToInterleavedRgbU8(ConvertYuv420_888.java:280)
        at boofcv.core.encoding.ConvertYuv420_888.yuvToBoof(ConvertYuv420_888.java:84)
        at boofcv.android.ConvertCameraImage.imageToBoof(ConvertCameraImage.java:57)
        at boofcv.android.camera2.VisualizeCamera2Activity.processFrame(VisualizeCamera2Activity.java:320)
        at boofcv.android.camera2.SimpleCamera2Activity.lambda$new$2$boofcv-android-camera2-SimpleCamera2Activity(SimpleCamera2Activity.java:1034)
        at boofcv.android.camera2.SimpleCamera2Activity$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:268)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.misc.BoofMiscOps.checkDeclare(BoofMiscOps.java:819)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.core.encoding.impl.ImplConvertYuv420_888.processYuv(ImplConvertYuv420_888.java:50)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.core.encoding.ConvertYuv420_888.yuvToInterleavedRgbU8(ConvertYuv420_888.java:280)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.core.encoding.ConvertYuv420_888.yuvToBoof(ConvertYuv420_888.java:84)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.android.ConvertCameraImage.imageToBoof(ConvertCameraImage.java:57)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.android.camera2.VisualizeCamera2Activity.processFrame(VisualizeCamera2Activity.java:320)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.android.camera2.SimpleCamera2Activity.lambda$new$2$boofcv-android-camera2-SimpleCamera2Activity(SimpleCamera2Activity.java:1034)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at boofcv.android.camera2.SimpleCamera2Activity$$ExternalSyntheticLambda0.onImageAvailable(Unknown Source:2)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at android.os.Handler.dispatchMessage(Handler.java:106)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at android.os.Looper.loop(Looper.java:268)
2022-08-10 14:01:53.320 3360-3430/org.boofcv.android I/ExceptionHandle:     at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by lessthanoptimal** [comment]
Flush your Gradle cache. If you're not sure how to do that just nuke it by deleting ~/.m2/repository  this issue is caused by a dependency on multiple developmental libraries.  A new stable release for BoofCV is going to happen soon, so that will end this chaos. If you are using IntelliJ or similar you might need to also flush your cache and restart it.

**Comment by YinXiuYu** [comment]
Thanks a lot for your quick reply and helping to solve the issue.

**Comment by lessthanoptimal** [comment]
Stable release has been out for about a month now. If you pull there should be no issues. Feel free to reopen if that's not the case.
