### ISSUE TITLE
Conversion of Bitmap (larger) to GrayU8 in android

### ISSUE THREAD

**Issue by shyamkumarm** [lessthanoptimal/BoofAndroidDemo#9]
Crash : java.lang.OutOfMemoryError: Failed to allocate a 387233296 byte allocation with 25165824 free bytes and 48MB until OOM, max allowed footprint 510792448, growth limit 536870912

Also i tried with 'android:largeHeap="true" ' in ManiFest File 

`Bitmap bitmap = ((BitmapDrawable) getResources().getDrawable(R.drawable.sample)).getBitmap();   GrayU8 grayU8 = ConvertBitmap.bitmapToGray(src, (GrayU8) null, null);`

**Comment by lessthanoptimal** [comment]
How big is this image? Assuming it died on allocating memory for the gray image, it looks like you are trying to allocate memory for a image that's very large. sqrt(387233296) = 19678. So about a 20k * 20k pixel image. It was trying to allocate an array of 369MB which most phones can handle, but there tends to be a lot of memory allocated in the background by Android when dealing with large images. Also if you could print the full stack trace that's more helpful. That way I know the line it's dying on.

**Comment by shyamkumarm** [comment]
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: a.b.android.s.dev, PID: 23104
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:366)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 159694864 byte allocation with 25165824 free bytes and 44MB until OOM, max allowed footprint 515687360, growth limit 536870912
        at boofcv.android.ConvertBitmap.declareStorage(ConvertBitmap.java:51)
        at boofcv.android.ConvertBitmap.bitmapToPlanar(ConvertBitmap.java:181)
        at a.b.s.edgev2.ZRectDetectManager$ImageBitmapCropper.doInBackground(ZRectDetectManager.java:561)
        at a.b.s.edgev2.ZRectDetectManager$ImageBitmapCropper.doInBackground(ZRectDetectManager.java:533)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 

        Mobile: Huawei p20 pro

        image Resolution : 5472 * 7296

        file size: 7.35 MB

**Comment by lessthanoptimal** [comment]
sorry for the very late reply. This just looks like a classic out of memory exception. Even high end devices have limited memory. Android OS also doesn't let any app have a huge amount of memory.
